name: Python package

on: [push]

jobs:
    docker-build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Test
          run: |
            cat ${BASE_64_CA_CERT}
          env:
            BASE_64_CA_CERT: ${{ secrets.DOCKER_REGISTRY_CA_CERT }}
