name: Python package

on: [push]

jobs:
    docker-build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Update CA certificates
          run: |
            echo ${CA_CERT} > /etc/ssl/certs/docker-registry-ca.crt && update-ca-certificates
          env:
            CA_CERT: ${{ secrets.DOCKER_REGISTRY_CA_CERT }}
