name: Python package

on: [push]

jobs:
    docker-build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Update CA certificates
          run: sudo cp .github/workflows/docker-registry-ca.crt /usr/local/share/ca-certificates/docker-registry-ca.crt && sudo update-ca-certificates

        - name: Install docker
          run: sudo apt-get install -y docker.io

        - name: Docker build
          run: docker build -t dcxkaeopvefubxjnaci.ddns.net:5000/github-webhook:test .


        # - name: Set up QEMU
        #   uses: docker/setup-qemu-action@v3

        # - name: Set up Docker Buildx
        #   uses: docker/setup-buildx-action@v3

        # - name: List
        #   run: ls -la /etc/docker/certs.d

        # - name: Build and push
        #   uses: docker/build-push-action@v5
        #   with:
        #     context: .
        #     push: true
        #     tags: dcxkaeopvefubxjnaci.ddns.net:5000/github-webhook:test
