name: Build and push Docker image

on:
  workflow_run:
    workflows: ["Unit tests"]
    types:
      - completed

jobs:
    docker-build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Update CA certificates
          run: sudo cp .github/workflows/docker-registry-ca.crt /usr/local/share/ca-certificates/docker-registry-ca.crt && sudo update-ca-certificates

        - name: Docker build
          run: docker build . -t $DOCKER_REGISTRY_SERVER/github-webhook:test
          env:
            DOCKER_REGISTRY_SERVER: ${{ secrets.DOCKER_REGISTRY_SERVER }}

        - name: Docker push
          run: docker push $DOCKER_REGISTRY_SERVER/github-webhook:test
          env:
            DOCKER_REGISTRY_SERVER: ${{ secrets.DOCKER_REGISTRY_SERVER }}
