name: Python package

on: [push]

jobs:
    docker-build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        # - name: Update CA certificates
        #   run: echo ${{ secrets.DOCKER_REGISTRY_CA_CERT }} > /tmp/ca-certificate.crt && sudo mv /tmp/ca-certificate.crt /usr/local/share/ca-certificates/ && sudo chmod 644 /usr/local/share/ca-certificates/ca-certificate.crt && sudo update-ca-certificates

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          env:
            DOCKER_CLI_EXPERIMENTAL: enabled
            DOCKER_TLS_VERIFY: 0

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: dcxkaeopvefubxjnaci.ddns.net:5000/github-webhook:test
          env:
            DOCKER_CLI_EXPERIMENTAL: enabled
            DOCKER_TLS_VERIFY: 0
