name: Build
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
    - uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '1.7.1'
    - name: Install the project dependencies
      run: poetry install
    - name: Run tests with pytest
      run: |
        poetry run coverage run --source=github,src -m pytest tests
    - name: Coverage report
      run: |
          poetry run coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4-beta
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - uses: docker/metadata-action@v5
      id: metadata
      with:
        images: ghcr.io/${{ github.repository }}
        labels: |
            org.opencontainers.image.description=Hemera is a Python library on top of Azure functions
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
