name: Python package

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.8
          uses: actions/setup-python@v4
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install coverage==7.3.2
            python -m pip install -r requirements.txt
            python -m pip install -r tests/requirements.txt
        - name: Run tests with pytest
          run: |
            python -m pytest tests
        - name: Run tests with coverage
          run: |
            python -m coverage run --source=package -m pytest tests
            python -m coverage report -m  