name: Unit tests and building docker image

on: [push, pull_request]

jobs:
    tests:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.8
          uses: actions/setup-python@v4
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install poetry==1.7.1
            poetry install
        - name: Run tests with pytest
          run: |
            poetry run coverage run --source=github,src -m pytest tests
        - name: Coverage report
          run: |
            poetry run coverage report -m
    build:
        needs: tests

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Update CA certificates
          run: sudo cp .github/workflows/docker-registry-ca.crt /usr/local/share/ca-certificates/docker-registry-ca.crt && sudo update-ca-certificates
        - name: Docker build
          run: docker build . -t $DOCKER_REGISTRY_SERVER/${{ github.repository }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'test' }}
          env:
            DOCKER_REGISTRY_SERVER: ${{ secrets.DOCKER_REGISTRY_SERVER }}
        - name: Docker push
          run: docker push $DOCKER_REGISTRY_SERVER/${{ github.repository }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'test' }}
          env:
            DOCKER_REGISTRY_SERVER: ${{ secrets.DOCKER_REGISTRY_SERVER }}
