name: Unit tests and building docker image
on: [push, pull_request]

jobs:
    build_docker_image:
        # needs: tests
        runs-on: ubuntu-latest
        env:
            DOCKER_IMAGE: ghcr.io/${{ github.repository }}:test
        steps:
        - uses: actions/checkout@v2
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.CR_PAT }}
        - uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ env.DOCKER_IMAGE }}
