name: Tests
on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.7.1
        poetry install
    - name: Install hadolint
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends wget
        sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
        sudo chmod +x /usr/local/bin/hadolint
    - name: Run pre-commit
      run: |
        poetry run pre-commit run --all-files
    - name: Run tests with pytest
      run: |
        poetry run coverage run --source=github,src -m pytest tests
    - name: Coverage report
      run: |
        poetry run coverage report -m
        poetry run coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/metadata-action@v5
      id: metadata
      with:
        images: ghcr.io/${{ github.repository }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
