name: Unit tests and building docker image

on: [push, pull_request]

jobs:
    tests:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
        - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
            virtualenvs-create: true
            virtualenvs-in-project: true
            installer-parallel: true
        - name: Install hadolint
          run: |
            apt-get update
            apt-get install -y --no-install-recommends wget
            wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x /usr/local/bin/hadolint
        - name: Run pre-commit
          run: |
            poetry run pre-commit run --all-files
        - name: Run tests with pytest
          run: |
            poetry run coverage run --source=github,src -m pytest tests
        - name: Coverage report
          run: |
            poetry run coverage report -m
    build:
        needs: tests

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Update CA certificates
          run: sudo cp .github/workflows/docker-registry-ca.crt /usr/local/share/ca-certificates/docker-registry-ca.crt && sudo update-ca-certificates
        - name: Docker build
          run: docker build . -t $DOCKER_REGISTRY_SERVER/${{ github.repository }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'test' }}
          env:
            DOCKER_REGISTRY_SERVER: ${{ secrets.DOCKER_REGISTRY_SERVER }}
        - name: Docker push
          run: docker push $DOCKER_REGISTRY_SERVER/${{ github.repository }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'test' }}
          env:
            DOCKER_REGISTRY_SERVER: ${{ secrets.DOCKER_REGISTRY_SERVER }}
