name: Unit tests and building docker image
on: [push, pull_request]

jobs:
    build_docker_image:
        # needs: tests
        runs-on: ubuntu-latest
        steps:
        - uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: false
            tags: ${{ github.repository }}:${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || (github.ref == 'refs/heads/master' && 'latest' || 'test') }}
