name: Unit tests and building docker image

on: [push, pull_request]

jobs:
    tests:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
        - name: Install poetry
          run: |
            python -m pip install --upgrade pip
            python -m pip install poetry==1.7.1
            poetry install
        - name: Install hadolint
          run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends wget
            sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            sudo chmod +x /usr/local/bin/hadolint
        - name: Run pre-commit
          run: |
            poetry run pre-commit run --all-files
        - name: Run tests with pytest
          run: |
            poetry run coverage run --source=github,src -m pytest tests
        - name: Coverage report
          run: |
            poetry run coverage report -m
    build:
        needs: tests

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Update CA certificates
          run: |
            echo "$DOCKER_REGISTRY_CA_CERT" | base64 --decode > ca.crt
            sudo mv ca.crt /usr/local/share/ca-certificates/ca.crt
            sudo chmod 644 /usr/local/share/ca-certificates/ca.crt
            sudo update-ca-certificates
          env:
            DOCKER_REGISTRY_CA_CERT:  ${{ secrets.DOCKER_REGISTRY_CA_CERT }}
        - name: Difference between files
          run: |
            diff .github/workflows/docker-registry-ca.crt /usr/local/share/ca-certificates/ca.crt
        - name: Docker build
          run: docker build . -t $DOCKER_REGISTRY_SERVER/${{ github.repository }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'test' }}
          env:
            DOCKER_REGISTRY_SERVER: ${{ secrets.DOCKER_REGISTRY_SERVER }}
        - name: Docker push
          run: docker push $DOCKER_REGISTRY_SERVER/${{ github.repository }}:${{ github.ref == 'refs/heads/master' && 'latest' || 'test' }}
          env:
            DOCKER_REGISTRY_SERVER: ${{ secrets.DOCKER_REGISTRY_SERVER }}
