name: Unit tests and building docker image
on: [push, pull_request]

jobs:
  build:
    # needs: tests
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}
      DOCKER_IMAGE_TAG: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || (github.ref == 'refs/heads/master' && 'latest' || 'test') }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ startsWith(github.ref, 'refs/tags/') && true || (github.ref == 'refs/heads/master' && true || false) }}
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG}}
