name: Unit tests and building docker image

on: [push, pull_request]

jobs:
    tests:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.8
          uses: actions/setup-python@v4
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install coverage==7.3.2
            python -m pip install -r requirements.txt
            python -m pip install -r tests/requirements.txt
        - name: Run tests with pytest
          run: |
            python -m coverage run --source=src -m pytest tests
        - name: Coverage report
          run: |
            python -m coverage report -m
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Update CA certificates
          run: sudo cp .github/workflows/docker-registry-ca.crt /usr/local/share/ca-certificates/docker-registry-ca.crt && sudo update-ca-certificates
        - name: Docker build
          run: docker build . -t $DOCKER_REGISTRY_SERVER/github-webhook:test
          env:
            DOCKER_REGISTRY_SERVER: ${{ secrets.DOCKER_REGISTRY_SERVER }}
        - name: Docker push
          run: docker push $DOCKER_REGISTRY_SERVER/github-webhook:test
          env:
            DOCKER_REGISTRY_SERVER: ${{ secrets.DOCKER_REGISTRY_SERVER }}
